name: Build Minecraft Plugin

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java Files
      run: |
        mkdir -p build/classes
        curl -sL https://spigotmc.org -o spigot.jar
        javac -d build/classes -cp spigot.jar src/com/info/Main.java
        cp plugin.yml build/classes/
        cd build/classes
        jar cf ../../PluginPertama.jar .

    - name: Upload Plugin Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PluginPertama-JAR
        path: PluginPertama.jar
        
